export const eventList = [
    "New year party",
    "Annual function",
    "Dhoti ceremony",
    "Half Saree",
    "First night",
    "Oh baby ",
    "Welcome Baby",
    "Bride to be ",
    "Groom to be",
    "Naming ceremony ",
    "Cradle ceremony ",
    "Annaprashan ceremony",
    "Anniversary",
    "Engagement Ceremony ",
    "Pre wedding ",
    "Wedding",
    "Home decor",
    "Cocktail party decor",
    "Proposal",
    "Festive",
    "Bachelor party",
    "Farewell party",
    "Office events",
    "Store opening (inauguration)",
    "Ring ceremony",
    "Conference backdrop setup",
    "Maternity ",
    "Family shoot",
    "1st Month baby",
    "Groom/Bride Entry",
    "Haldi & Mehandi",
    "Coorporate",
    "Birthday",
    "Baby Shower",
    "Seemantham",
    "Dohale Jevan",
    "Godh Bharai",
    "Chatti",
    "Naming Ceremony",
    "Namkaran",
    "Annaprashan",
    "Choroonu",
    "Hatey Khori",
    "Vidyarambham",
    "First Birthday",
    "Half Birthday",
    "First Tooth Celebration",
    "First Walk Ceremony",
    "Ayush Homam",
    "Pet Birthday",
    "Proposal Party",
    "Dating Anniversary",
    "Valentine's Day Party",
    "Pre-Engagement",
    "Engagement",
    "Roka Ceremony",
    "Haldi",
    "Mehendi",
    "Sangeet",
    "Tilak Ceremony",
    "Bou Bhaat",
    "Mameru",
    "Reception",
    "Post-Wedding Party",
    "Gender Reveal",
    "Housewarming",
    "Griha Pravesh",
    "Satyanarayan Puja",
    "Ramayan Katha",
    "Vrat Udyapan",
    "Thread Ceremony (Upanayan)",
    "Thread Ceremony for Girls",
    "Baptism",
    "Christening",
    "Eid",
    "Iftar",
    "Diwali",
    "Holi",
    "Karva Chauth Udyapan",
    "Kitty Party",
    "Raksha Bandhan",
    "Navratri",
    "Dussehra",
    "Ganesh Chaturthi",
    "Onam",
    "Durga Puja",
    "Pongal",
    "Makar Sankranti",
    "Lohri",
    "Bihu",
    "Ugadi",
    "Gudi Padwa",
    "Vishu",
    "Mahavir Jayanti",
    "Guru Nanak Jayanti",
    "Janmashtami",
    "Baisakhi",
    "Karva Chauth",
    "Chhath Puja",
    "Game Night",
    "Tambola",
    "Housie Party",
    "Poker Night",
    "Retirement",
    "Pet Welcome",
  ];